### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by flatlinebb** [KvanTTT/NppGist#12]
I got a notification from GitHub when using the plugin, that the authentication method used is depreciated:

>Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
>
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team

Is this something you will be able to address? I love your plugin, but I don't want to use it if the auth is not secure and discouraged by Github.

**Comment by KvanTTT** [comment]
Thanks. I'll take a look.

**Comment by d3artagnan** [comment]
+1

**Comment by KvanTTT** [comment]
I've fixed it eventually. Could you please check if this issue is resolved in the latest build? https://ci.appveyor.com/project/KvanTTT/nppgist/branch/master

**Comment by flatlinebb** [comment]
The new build, 1.4.0.23 does not appear to be triggering the warning from GitHub. And it is able to download and upload gists. So I would say the issue is fixed. Thank you so much!
