### ISSUE TITLE
Limited to 30 gists?

### ISSUE THREAD

**Issue by agail** [KvanTTT/NppGist#13]
I have 50+ gists but only 29 is showing in the open dialog box.
Is there a limit?

BR Agail

**Comment by KvanTTT** [comment]
I don't think so, it's quite strange.

**Comment by agail** [comment]
Correction, it is showing 30, not 29 as I initially wrote.

I have a script that lists my gists and it has the same issue, only showing 30 of 52 gists,
Digging further I found out the API changed a bit.:
https://docs.github.com/en/rest/reference/gists#list-gists-for-a-user
https://developer.github.com/v3/#pagination

<authenticated session> 
curl https://api.github.com/users/{username}/gists | jq-win64 ".[]|.files[].filename" gistout.json | wc -l
30

<authenticated session>
curl "https://api.github.com/users/{username}/gists?page=1&per_page=100" | jq-win64 ".[]|.files[].filename" gistout.json | wc -l
52

**Comment by KvanTTT** [comment]
It looks like we should implement pagination.

**Comment by KvanTTT** [comment]
I'm going to implement pagination ASAP.

**Comment by KvanTTT** [comment]
I've implemented it, check in the latest build: https://ci.appveyor.com/project/KvanTTT/nppgist/builds/35063667

**Comment by agail** [comment]
Running npp 7.8.9 x64
```
Failed to load

NppGist.dll is not compatible with the current version of Notepad++.

Do you want to remove this plugin from the plugins directory to prevent this message from the next launch?

```

**Comment by KvanTTT** [comment]
It works fine on my computer (1.4.0.24). Could you please check the x86 version?

**Comment by agail** [comment]
Same issue with npp 7.8.9 x86

Also, I found this in my inbox from github

```
On September 5th, 2020 at 20:44 (UTC) your personal access token (notepad++) using NppGist was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

**Comment by KvanTTT** [comment]
Such an issue is definitely resolved, I and another user have checked it, see #12 It seems like you are trying not the latest version.

**Comment by agail** [comment]
Good to know, I missed that, sorry.
I’ll try your .23 release when I get back to see if that also trigger the error message.
Stay tuned ..

**Comment by agail** [comment]
Success, well sort of anyway ;)

I went ahead and tried npp 7.8.8 and 7.8.9 with nppGist 1.4.0.23 and 1.4.0.24, both x86 and x64.
Still same issue, then I realized it might be my win7 :facepalm:
Works as expected on my win10 :ok_hand: 

Is win7 supported at all or am I missing some dependencies perhaps? (yeah, I know its no longer supported by MS, but still.)

**Comment by KvanTTT** [comment]
Maybe it's something related to the .NET framework version? What version do you have installed on Win 7?

**Comment by KvanTTT** [comment]
Could you please check the latest version https://ci.appveyor.com/project/KvanTTT/nppgist/builds/35074108 on your win 7 system?

**Comment by agail** [comment]
Works like a charm! Thanks for your patience!

_My system is running .net client/full: 4.7.02558_
