### ISSUE TITLE
Icon not visible with Notepad++ dark theme

### ISSUE THREAD

**Issue by dartraiden** [KvanTTT/NppGist#18]
Notepad++ v8.0 introduced the possibility for a dark ui-theme.  Plugin authors need to call `NPPM_ADDTOOLBARICON_FORDARKMODE` instead of `NPPM_ADDTOOLBARICON` for Notepad++ v8.0 or newer. 

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9928

**Comment by KvanTTT** [comment]
It seems like I know how to fix it, I'm going to do it ASAP.

**Comment by KvanTTT** [comment]
Done. Please try the new version from artifact: https://ci.appveyor.com/project/KvanTTT/nppgist/build/job/dukh60x6gpeteeta/artifacts

**Comment by dartraiden** [comment]
The icon is now visible, thanks!
