### ISSUE TITLE
Saving gist crashes Notepadplusplus

### ISSUE THREAD

**Issue by flatlinebb** [KvanTTT/NppGist#20]
It was working a few weeks ago, and now the whole NPP app crashes when trying to update an existing gist. No error message. Could be due to a recent NPP version update. I updated the Access Token with a new one in the plugin, but it did not help. Running NotepadPlusPlus ver. 8.3.1, and the NppGist plugin ver. 1.5.0.31.

**Comment by KvanTTT** [comment]
Unfortunately it's not reproducable for me.

**Comment by flatlinebb** [comment]
Also, have you seen this forum post on the NP++ forum:
https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header
It seems like it applies to NppGist.

**Comment by KvanTTT** [comment]
I don't exacly understand how to fix the issue. Maybe you could suggest a pull request?

**Comment by flatlinebb** [comment]
I don't know anything about writing NP++ plugins, so I am of no help in this regard. Maybe reach out to the NP++ author and see if there is something he can suggest. Or check the plugin design forums: https://community.notepad-plus-plus.org/category/5/plugin-development.

**Comment by KvanTTT** [comment]
Done. Please try if the new version works fine https://ci.appveyor.com/project/KvanTTT/nppgist/branch/master

**Comment by flatlinebb** [comment]
The updated version works great! No more crashes and the gists are updating. Thank you so much for your hard work - it is very appreciated.
