### ISSUE TITLE
Not Notepad++ Unicode Compliant, will not open in modern NP++

### ISSUE THREAD

**Issue by chrstfer** [KvanTTT/NppGist#4]
The ASCII plugins are no longer supported whatsoever by Notepad++; it won't even load the plugin if it isn't Unicode. I saw this plugin and was intrigued, but I can't load it so I can't get any use out of it, nor can anyone else who might want to. I don't know C#, or I'd try to convert it myself, but I can't.

**Comment by KvanTTT** [comment]
Probably it makes sense to update plugin platform.

**Comment by KvanTTT** [comment]
Try a new version [1.1](https://github.com/KvanTTT/NppGist/releases/tag/1.1).
