### ISSUE TITLE
После установки плагина не работает XML Tools 

### ISSUE THREAD

**Issue by CoreText** [KvanTTT/NppGist#5]
Видимо какой-то конфликт

**Comment by KvanTTT** [comment]
Что именно не работает? У меня работает, во всяком случае Pretty Print. Попробуйте новую версию [1.1](https://github.com/KvanTTT/NppGist/releases/tag/1.1).

**Comment by KvanTTT** [comment]
Переоткройте если все еще воспроизводится.
