### ISSUE TITLE
Вообще не работает опция сохранить

### ISSUE THREAD

**Issue by bible-man** [KvanTTT/NppGist#6]
Просто сразу падает  Npp 7.4.2 на win10
Не планируете ли обновить плагин до рабочей версии?

**Comment by KvanTTT** [comment]
Вряд ли. Работа над плагином больше не ведётся.

**Comment by ayazzali** [comment]
хочу починить это (-- тоже самое на 7-ке 64bit и вин 8.0 64bit. NPP везде 32bit).
только не знаю как отладить прям на "продакшене"- когда падает в самом npp. 
крч отпишусь.

**Comment by KvanTTT** [comment]
Ну попробуй :) Может стоит использовать логгирование исключений и других событий?

**Comment by ayazzali** [comment]
Попробовал безнадёжно.
С помощью msbuild еле сбидил,
А вот эта длл-ка не подцепилась нотпадом-
 он сказал, что ANSI не подходит для меня(нотпада) используйте юникод, и предложил удалить эту дллку(мою сбилденную)

**Comment by ayazzali** [comment]
На английской винде даже билдил. Илдасм открывает дллку.- значит нормальная , тип понимаю).
Сталкивались с таким?
P.s. тоже логи хотел поставить - крашится в утилс.гетДжсонРеквест - что то с соединением

**Comment by KvanTTT** [comment]
Да, у меня подобная ошибка показывалась. ildasm не причем - возможно конфликт в версиях API и нужно просто его обновить как я уже сказал. Попробуй посмотреть как этот более современный проект устроен, работает ли: https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net

**Comment by KvanTTT** [comment]
Исправлено в #7
