### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by dartraiden** [KvanTTT/NppGist#8]
Please, compile also x64 version
https://notepad-plus-plus.org/community/topic/12053/notepad-plugin-template-plugin-demo-x64-build-available

**Comment by KvanTTT** [comment]
I compiled x64 version, but icons not shown in toolbar :(
I don't know how can I fix it.

**Comment by KvanTTT** [comment]
Can you try to fix it? I pushed changes for x86 and x64 configs.

**Comment by KvanTTT** [comment]
Found out the problem. I'll fix it tomorrow.

**Comment by KvanTTT** [comment]
Done: https://github.com/KvanTTT/NppGist/releases/tag/1.2
